version: '3.5'
services:

  #PHP Service
  control:
    build:
      context: .
      dockerfile: Dockerfile
    image: github.com/joseluis21/laravel2
    container_name: control
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: control
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports: 
      - "9001:9000"
    volumes:
      - ./controlpvta:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - my-proxy-net

  #Nginx Service
  webserver2:
    image: nginx
    container_name: webserver2
    restart: unless-stopped
    tty: true
    depends_on:
      - control
    ports:
      - "8080:80"
    volumes:
      - ./controlpvta:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      # - ./nginx/:/etc/nginx/
    networks:
      - my-proxy-net

#Docker Networks
networks:
  my-proxy-net:
    external:
      name: apps-network

#docker-compose up -d
#docker-compose down //Elimina todo los contenedores
#docker-compose exec control composer install
#docker-compose exec control php artisan key:generate
#docker-compose exec control php artisan migrate --seed
#docker-compose exec control php artisan config:cache
#docker-compose stop
#docker rm -f ID
#docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=12345678 -p 3306:3306 -d mysql